### ISSUE TITLE
Clean Code architecture

### ISSUE THREAD

**Issue by tushar1210** [tushar1210/manga-node#106]
Need to settle upon schema of interfaces, nomenclature of methods, properties, and interfaces.
@saqsham suggestions?

**Comment by saqsham** [comment]
ok so, directory names should be smallcase
functions - camelCase
endpoints - smallcase
class names - PascalCase
variables - camelCase
all static content should go to the public dir, (need to move src/sources.json)

In helpers/mangakakalot you put the Scrapper code, instead put the code/file in Models ? same for mangasee Scrapper, I recommend making the `hotUpdates` and other related functions in Models or in Scrapper itself, at one place I mean.

**Comment by tushar1210** [comment]
- [ ] directories
- [ ] functions
- [ ] endpoints
- [ ] class names
- [ ] variables
- [ ] public dis

**Comment by saqsham** [comment]
We should maintain two apps, right ? One for user auth etc. stuff and other for manga-node.
The api key will be attached with each user's account, and will be used in header for fetching data.
so remove the sqlz dir I guess and the related packages.

**Comment by tushar1210** [comment]
@saqsham yes i guess it will be better that way, if you want you can make a fresh repo.

**Comment by tushar1210** [comment]
All advised changes are made
